name: Post new thing to Obama Nostalgia twitter account

on: [push, workflow_dispatch]

jobs:
  post:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 
    # You can test your matrix by printing the current Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Post to Twitter
      run: ./post.py